server:
  port: 8080
management:
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: demo-provider
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://127.0.0.1:3306/demo?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: mysql
      hikari:
        auto-commit: true
        connection-test-query: SELECT 1
        connection-timeout: 30000
        idle-timeout: 30000
        max-lifetime: 1800000
        maximum-pool-size: 15
        minmum-idle: 5
        pool-name: DatebookHikariCP
mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.example.demospringboot.dal.dao
  type-handlers-package: org.apache.ibatis.type.LocalDateTypeHandler
logging:
  config: classpath:logback.xml
